export const DEFAULT_INVITATION_SETTINGS = {
  rsvp_settings: {
    rsvp_status: 1,
    custom_inputs: [],
    inputs: [
      {
        name: "name",
        type: "text",
        label: "Nama",
        placeholder: "Contoh: Budi Darmawan",
        required: true,
        is_disabled: false,
        is_published: true,
      },
      {
        name: "group_name",
        type: "text",
        label: "Grup",
        placeholder: "Contoh: Keluarga Besar / Teman SMA",
        required: false,
        is_disabled: false,
        is_published: true,
      },
      {
        name: "phone",
        type: "phone",
        label: "No WhatsApp",
        placeholder: "Contoh: 08123456789",
        required: true,
        is_disabled: false,
        is_published: true,
      },
      {
        name: "attendance",
        type: "select",
        label: "Kehadiran",
        value: "Hadir,Tidak Hadir",
        placeholder: "Pilih status kehadiran",
        showqr: "Hadir",
        required: true,
        showguest: "Hadir",
        is_disabled: false,
        is_published: true,
      },
      {
        name: "guest_count",
        type: "guest",
        label: "Jumlah Tamu",
        value: "2",
        placeholder: "Pilih jumlah orang",
        required: true,
        is_disabled: false,
        is_published: true,
      },
      {
        name: "comment",
        type: "textarea",
        label: "Komentar atau Ucapan",
        placeholder: "Tulis ucapan selamat dan doa restu untuk mempelai...",
        required: true,
        is_disabled: false,
        is_published: true,
      },
    ],
    is_private: false,
    show_comments: true,
    show_download_qr: true,
    default_country_code: 62,
    show_update_confirmation: true,
  },
};
